#Casino
PROBABILIDAD_EVENTO = 0.1


#Jugador
PORCENTAJE_APUESTA_TACANO = 0.2
BONIFICACION_TACANO = 50
MULTIPLICADOR_BONIFICACION_BEBEDOR = 1.5
BONIFICACION_SUERTE_CASUAL = 0.1

#Juego
FRUSTRACION_PERDER = 6
CONFIANZA_PERDER = 3
EGO_GANAR = 10
CARISMA_GANAR = 3
FRUSTRACION_GANAR = 4

#Bebestibles

MIN_ENERGIA_BEBESTIBLE = 5
MAX_ENERGIA_BEBESTIBLE = 50